import { ADDRESSES, ARC, DEPLOY_BLOCK } from '@predex-pump/shared';

import { testPrisma } from './database.js';

export const DEPLOYER = '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
export const TRADER = '0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';
export const OTHER_CREATOR = '0xcccccccccccccccccccccccccccccccccccccccc';
export const SIGNER_ONE = '0xdddddddddddddddddddddddddddddddddddddddd';
export const SIGNER_TWO = '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee';
export const MARKET_ONE_CONDITION = `0x${'1'.repeat(64)}`;
export const MARKET_TWO_CONDITION = `0x${'2'.repeat(64)}`;
export const MARKET_ONE_QUESTION = `0x${'3'.repeat(64)}`;
export const MARKET_TWO_QUESTION = `0x${'4'.repeat(64)}`;
export const TRADE_TX = `0x${'5'.repeat(64)}`;
export const CREATED_TX = `0x${'6'.repeat(64)}`;

export async function seedContractData(): Promise<void> {
  await testPrisma.registryConfig.create({
    data: {
      id: 1,
      chainId: ARC.chainId,
      usdcAddress: ADDRESSES.usdc.toLowerCase(),
      ctfAddress: ADDRESSES.ctf.toLowerCase(),
      oracleAddress: ADDRESSES.oracle.toLowerCase(),
      lmsrAddress: ADDRESSES.lmsr.toLowerCase(),
      registryAddress: ADDRESSES.registry.toLowerCase(),
      miniClobAddress: ADDRESSES.miniClob.toLowerCase(),
      marketTypeVersion: 2,
      currentLmsrAddress: ADDRESSES.lmsr.toLowerCase(),
      seedFloorRaw: '1000000',
      seedCapRaw: '50000000',
      graduationTollRaw: '2000000',
      protocolFeeBps: 100,
      minTradingWindowSeconds: 3600,
      maxTradingWindowSeconds: 604800,
      committeeThreshold: 2,
      updatedBlock: 100,
    },
  });
  await testPrisma.indexerState.create({
    data: {
      id: 1,
      chainId: ARC.chainId,
      deployBlock: DEPLOY_BLOCK,
      lastBlock: 100,
      headBlock: 103,
      lastSuccessfulPollAt: new Date(),
      chainStateBootstrapStatus: 'COMPLETE',
      chainStateBootstrapAttemptedBlock: 100,
      chainStateBootstrapBlock: 100,
      chainStateBootstrapAttemptedAt: new Date(),
      chainStateBootstrappedAt: new Date(),
    },
  });
  await testPrisma.indexerSubscriptionState.create({
    data: {
      id: 1,
      status: 'connected',
      headBlock: 103,
      lastMessageAt: new Date(),
    },
  });
  await testPrisma.committeeMember.createMany({
    data: [
      {
        address: SIGNER_ONE,
        active: true,
        addedAt: 1_700_000_000,
        updatedBlock: 90,
      },
      {
        address: SIGNER_TWO,
        active: true,
        addedAt: 1_700_000_001,
        updatedBlock: 91,
      },
    ],
  });
  await testPrisma.registeredMarketType.create({
    data: {
      version: 2,
      lmsrAddress: ADDRESSES.lmsr.toLowerCase(),
      configHash: `0x${'f'.repeat(64)}`,
      registeredAt: 1_700_000_000,
      blockNumber: 90,
      logIndex: 0,
    },
  });
  await testPrisma.account.createMany({
    data: [
      {
        address: DEPLOYER,
        firstSeenAt: 1_700_000_000,
        marketsCreated: 1,
        tradeCount: 0,
      },
      {
        address: TRADER,
        firstSeenAt: 1_700_000_010,
        marketsCreated: 0,
        tradeCount: 1,
        realizedPnlRaw: '100000',
        unrealizedPnlRaw: '500000',
      },
      {
        address: OTHER_CREATOR,
        firstSeenAt: 1_700_000_100,
        marketsCreated: 1,
        tradeCount: 0,
      },
    ],
  });
  await testPrisma.market.create({
    data: {
      id: '1',
      creator: DEPLOYER,
      question: 'Will the first market graduate?',
      ancillaryData: '0x57696c6c20746865206669727374206d61726b65742067726164756174653f',
      ancillaryDataHash: `0x${'7'.repeat(64)}`,
      metadataHash: `0x${'8'.repeat(64)}`,
      phase: 'Graduated',
      conditionId: MARKET_ONE_CONDITION,
      questionId: MARKET_ONE_QUESTION,
      marketTypeVersion: 2,
      collateralAddress: ADDRESSES.usdc.toLowerCase(),
      collateralDecimals: 6,
      yesTokenId: '101',
      noTokenId: '102',
      seedRaw: '10000000',
      yesPriceRaw: '600000',
      noPriceRaw: '400000',
      graduationActivityRaw: '25000000',
      bookAddress: ADDRESSES.miniClob.toLowerCase(),
      frozenYesPriceRaw: '600000',
      handoffSizeRaw: '5000000',
      tradeCount: 1,
      volumeRaw: '1000000',
      seedFloorRaw: '1000000',
      seedCapRaw: '50000000',
      fCapRaw: '100000000',
      graduationThresholdRaw: '25000000',
      graduationTollRaw: '2000000',
      inventoryTargetRaw: '5000000',
      protocolFeeBps: 100,
      depthFeeBps: 50,
      tradingWindowSeconds: 86400,
      minimumTimeOpenSeconds: 3600,
      createdAt: 1_700_000_000,
      tradingEndsAt: 1_700_086_400,
      graduatedAt: 1_700_003_600,
    },
  });
  await testPrisma.market.create({
    data: {
      id: '2',
      creator: OTHER_CREATOR,
      question: 'Did the second market resolve YES?',
      ancillaryData: '0x',
      ancillaryDataHash: `0x${'9'.repeat(64)}`,
      metadataHash: `0x${'a'.repeat(64)}`,
      phase: 'ResolvedObserved',
      conditionId: MARKET_TWO_CONDITION,
      questionId: MARKET_TWO_QUESTION,
      marketTypeVersion: 2,
      collateralAddress: ADDRESSES.usdc.toLowerCase(),
      collateralDecimals: 6,
      yesTokenId: '201',
      noTokenId: '202',
      seedRaw: '2000000',
      yesPriceRaw: '550000',
      noPriceRaw: '450000',
      seedFloorRaw: '1000000',
      seedCapRaw: '50000000',
      fCapRaw: '100000000',
      graduationThresholdRaw: '25000000',
      graduationTollRaw: '2000000',
      inventoryTargetRaw: '5000000',
      protocolFeeBps: 100,
      depthFeeBps: 50,
      tradingWindowSeconds: 86400,
      minimumTimeOpenSeconds: 3600,
      createdAt: 1_700_000_100,
      tradingEndsAt: 1_700_086_500,
      resolvedAt: 1_700_010_000,
    },
  });
  await testPrisma.resolution.create({
    data: {
      marketId: '2',
      conditionId: MARKET_TWO_CONDITION,
      outcome: 'YES',
      payoutYes: 1,
      payoutNo: 0,
      denominator: 1,
      resolvedAt: 1_700_010_000,
      observedAt: 1_700_010_100,
      txHash: `0x${'b'.repeat(64)}`,
      logIndex: 2,
    },
  });
  await testPrisma.trade.create({
    data: {
      id: `${TRADE_TX}:4`,
      marketId: '1',
      venue: 'LMSR',
      account: TRADER,
      recipient: TRADER,
      outcome: 'YES',
      side: 'BID',
      sizeRaw: '2000000',
      priceRaw: '500000',
      costRaw: '1000000',
      feeRaw: '10000',
      baseAmountRaw: '990000',
      protocolFeeRaw: '6000',
      depthContributionRaw: '4000',
      totalCostRaw: '1000000',
      netProceedsRaw: '0',
      txHash: TRADE_TX,
      logIndex: 4,
      blockNumber: 95,
      ts: 1_700_000_010,
    },
  });
  await testPrisma.pricePoint.createMany({
    data: [
      {
        id: `${TRADE_TX}:5`,
        marketId: '1',
        yesPriceRaw: '550000',
        noPriceRaw: '450000',
        qYesRaw: '1000000',
        qNoRaw: '0',
        bCurrentWad: '1000000000000000000',
        txHash: TRADE_TX,
        logIndex: 5,
        blockNumber: 95,
        ts: 1_700_000_010,
      },
      {
        id: `${TRADE_TX}:6`,
        marketId: '1',
        yesPriceRaw: '600000',
        noPriceRaw: '400000',
        qYesRaw: '2000000',
        qNoRaw: '0',
        bCurrentWad: '1000000000000000000',
        txHash: TRADE_TX,
        logIndex: 6,
        blockNumber: 96,
        ts: 1_700_000_020,
      },
    ],
  });
  await testPrisma.position.create({
    data: {
      account: TRADER,
      marketId: '1',
      outcome: 'YES',
      qtyRaw: '2000000',
      costBasisRaw: '700000',
      costBasisEstimated: true,
      realizedPnlRaw: '100000',
      unrealizedPnlRaw: '500000',
      updatedAt: 1_700_000_020,
    },
  });
  await testPrisma.order.createMany({
    data: [
      {
        orderId: '1',
        marketId: '1',
        conditionId: MARKET_ONE_CONDITION,
        tokenId: '101',
        outcome: 'YES',
        maker: DEPLOYER,
        side: 'BID',
        priceRaw: '600000',
        sizeRaw: '1000000',
        escrowRaw: '600000',
        filledRaw: '250000',
        remainingRaw: '750000',
        open: true,
        isSeed: false,
        txHash: `0x${'c'.repeat(64)}`,
        logIndex: 1,
        blockNumber: 97,
        createdAt: 1_700_003_600,
        updatedAt: 1_700_003_700,
      },
      {
        orderId: '2',
        marketId: '1',
        conditionId: MARKET_ONE_CONDITION,
        tokenId: '101',
        outcome: 'YES',
        maker: DEPLOYER,
        side: 'BID',
        priceRaw: '600000',
        sizeRaw: '500000',
        escrowRaw: '300000',
        filledRaw: '0',
        remainingRaw: '500000',
        open: true,
        isSeed: true,
        txHash: `0x${'d'.repeat(64)}`,
        logIndex: 2,
        blockNumber: 97,
        createdAt: 1_700_003_601,
        updatedAt: 1_700_003_601,
      },
      {
        orderId: '3',
        marketId: '1',
        conditionId: MARKET_ONE_CONDITION,
        tokenId: '101',
        outcome: 'YES',
        maker: DEPLOYER,
        side: 'ASK',
        priceRaw: '650000',
        sizeRaw: '1000000',
        escrowRaw: '1000000',
        filledRaw: '0',
        remainingRaw: '1000000',
        open: true,
        isSeed: true,
        txHash: `0x${'e'.repeat(64)}`,
        logIndex: 3,
        blockNumber: 97,
        createdAt: 1_700_003_602,
        updatedAt: 1_700_003_602,
      },
    ],
  });
  await testPrisma.activityEvent.createMany({
    data: [
      {
        id: `${CREATED_TX}:0`,
        type: 'MarketCreated',
        eventName: 'MarketCreated',
        source: 'REGISTRY',
        marketId: '1',
        account: DEPLOYER,
        txHash: CREATED_TX,
        logIndex: 0,
        blockNumber: 90,
        ts: 1_700_000_000,
        data: {},
      },
      {
        id: `${TRADE_TX}:4`,
        type: 'Trade',
        eventName: 'TradeExecuted',
        source: 'LMSR',
        marketId: '1',
        account: TRADER,
        outcome: 'YES',
        side: 'BID',
        amountRaw: '2000000',
        priceRaw: '500000',
        txHash: TRADE_TX,
        logIndex: 4,
        blockNumber: 95,
        ts: 1_700_000_010,
        data: {},
      },
      {
        id: `${TRADE_TX}:5`,
        type: 'TradeState',
        eventName: 'TradeState',
        source: 'LMSR',
        marketId: '1',
        account: null,
        txHash: TRADE_TX,
        logIndex: 5,
        blockNumber: 95,
        ts: 1_700_000_010,
        data: {},
      },
    ],
  });
}
